### ISSUE TITLE
Eine zentrale Log-Datei

### ISSUE THREAD

**Issue by mhebing** [ddionrails/testsuite#18]
- [x] Eine zentrale Log-Datei
- [ ] Unterscheidungen von Info, Warning und Error
- [ ] Aus jeder Fehlermeldung sollte deutlich werden, in welchem Prozessschritt sie passiert ist
- [ ] Flag in der main.py setzen, welches das Debug-Level definiert

## Resources

Leichte Lektüre:

- https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/
- https://www.digitalocean.com/community/tutorials/how-to-use-logging-in-python-3

Original Docu, vermutlich etwas schwere Kost:

- https://docs.python.org/3/howto/logging.html
- https://docs.python.org/3/howto/logging-cookbook.html
- https://docs.python.org/3/library/logging.html

**Comment by mhebing** [comment]
https://docs.python.org/3/library/argparse.html

**Comment by mpahl** [comment]
Ausprobieren, ob eine Klasse in settings.py (neu) mittels argv.
In der main.py --debug=debug benutzen.
