### ISSUE TITLE
Find pandas function for density distribution

### ISSUE THREAD

**Issue by mhebing** [ddionrails/testsuite#5]

**Comment by mhebing** [comment]
@mpahl Hab jetzt endlich einen Weg gefunden, um die Density Funktion in Python zu berechnen :smiley: 

``` python
from scipy.stats import gaussian_kde
import numpy as np
import pandas as pd

NUM_ELEMENTS = 30
example = np.array([1, 1, 1, 2, 5, 10])

# Die nächsten zwei Zeilen sind die entscheidenden:

density_range = np.linspace(example.min(), example.max(), NUM_ELEMENTS)
density = gaussian_kde(example).evaluate(density_range)

pd.DataFrame(dict(
    x = density_range,
    y = density,
))
```

**Comment by mpahl** [comment]
see https://github.com/ddionrails/ddi.py/commit/468d747a06ce117f5a82b663eface8836984c1bb

**Comment by mpahl** [comment]
Mich wundert nur, dass die Summe der Werte nicht 1 ergibt. Sollte das nicht der Fall sein?

**Comment by mhebing** [comment]
Das ist bei der Density etwas anders: Wenn Du die Ergebnisse als Graph zeichnest, dann soll die Fläche (!) unter dem Graph 1 ergeben. Dass heißt aber, dass die Summe der einzelnen Werte nicht 1 ergeben muss.
